apiVersion: apps/v1
kind: Deployment
metadata:
  name: bikes-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bikes-app
  template:
    metadata:
      labels:
        app: bikes-app
    spec:
      containers:
      - name: bikes-app
        image: maheshsoft/bikes_shop:latest
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: bikes-service
spec:
  type: NodePort
  selector:
    app: bikes-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30033
