apiVersion: apps/v1
kind: Deployment
metadata:
  name: fans-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: fans-app
  template:
    metadata:
      labels:
        app: fans-app
    spec:
      containers:
      - name: fans-app
        image: maheshsoft/fans_shop:latest0dc60534ee3d
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: fans-service
spec:
  type: NodePort
  selector:
    app: fans-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30033
