name: deployment workflow for k8s
on:
  workflow_dispatch:   # manual trigger
 # push:
 #   branches: ["main"]

jobs:
  deploy:
    runs-on: self-hosted   # windoes laptop runner this one 
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Deploy FansApp to Kubernetes
        run: |
          kubectl apply -f appstore/fansapp/k8s/fans_deploy.yaml
      - name: Validate my deployemnts 
        run: |
          kubectl get deployment fans-app
